language: c
sudo: false
branches:
only:
  - master
os:
  - linux
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes psutil yaml pyyaml
  - conda-env create -f code/install_gds_stack.yml
  - source activate gds

script: 
  - jupyter nbconvert --execute --ExecutePreprocessor.timeout=480 code/check_gds_stack.ipynb

